import { isoDateOnly, isoDays } from "./lib";
import type { AppState, User } from "./types";

const users: User[] = [
  {
    id: "u1",
    name: "Иванова Анна Сергеевна",
    shortName: "Иванова А.",
    role: "specialist",
    position: "Специалист ОТ / ПБиЭ",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Центральная»",
    workshop: "Административный корпус",
    birthday: "03-14",
    email: "a.ivanova@nhtk.local",
    phone: "+7 8555 31-20-14",
    initials: "ИА",
    hired: "2018-04-02",
    profession: "Специалист по охране труда",
  },
  {
    id: "u2",
    name: "Петров Сергей Николаевич",
    shortName: "Петров С.",
    role: "employee",
    position: "Аппаратчик 5 разряда",
    department: "Производство полимеров",
    site: "Площадка «Центральная»",
    workshop: "Цех полимеров №1",
    birthday: "03-21",
    email: "s.petrov@nhtk.local",
    phone: "+7 8555 31-44-02",
    initials: "ПС",
    hired: "2014-09-15",
    profession: "Аппаратчик",
  },
  {
    id: "u3",
    name: "Козлов Дмитрий Павлович",
    shortName: "Козлов Д.",
    role: "trainer",
    position: "Внутренний тренер по безопасности",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Центральная»",
    workshop: "Административный корпус",
    birthday: "06-02",
    email: "d.kozlov@nhtk.local",
    phone: "+7 8555 31-20-22",
    initials: "КД",
    hired: "2016-02-01",
    profession: "Тренер HSE",
  },
  {
    id: "u4",
    name: "Соколова Елена Викторовна",
    shortName: "Соколова Е.",
    role: "manager",
    position: "Руководитель департамента ОТ, ПБиЭ",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Центральная»",
    workshop: "Административный корпус",
    birthday: "11-21",
    email: "e.sokolova@nhtk.local",
    phone: "+7 8555 31-20-01",
    initials: "СЕ",
    hired: "2011-03-10",
    profession: "Руководитель",
  },
  {
    id: "u5",
    name: "Морозов Игорь Александрович",
    shortName: "Морозов И.",
    role: "admin",
    position: "Администратор портала",
    department: "ИТ / HSE-портал",
    site: "Площадка «Центральная»",
    workshop: "Административный корпус",
    birthday: "01-09",
    email: "i.morozov@nhtk.local",
    phone: "+7 8555 31-18-90",
    initials: "МИ",
    hired: "2020-11-01",
    profession: "Администратор",
  },
  {
    id: "u6",
    name: "Волкова Мария Андреевна",
    shortName: "Волкова М.",
    role: "specialist",
    position: "Инженер-эколог",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Северная»",
    workshop: "Очистные сооружения",
    birthday: "04-04",
    email: "m.volkova@nhtk.local",
    phone: "+7 8555 31-55-11",
    initials: "ВМ",
    hired: "2019-07-22",
    profession: "Эколог",
  },
  {
    id: "u7",
    name: "Новиков Алексей Петрович",
    shortName: "Новиков А.",
    role: "employee",
    position: "Начальник смены",
    department: "Производство мономеров",
    site: "Площадка «Восточная»",
    workshop: "Установка пиролиза",
    birthday: "08-17",
    email: "a.novikov@nhtk.local",
    phone: "+7 8555 31-62-08",
    initials: "НА",
    hired: "2012-05-14",
    profession: "Начальник смены",
  },
  {
    id: "u8",
    name: "Смирнова Ольга Игоревна",
    shortName: "Смирнова О.",
    role: "employee",
    position: "Кладовщик СИЗ",
    department: "МТО",
    site: "Площадка «Центральная»",
    workshop: "Склад ГСМ",
    birthday: "12-03",
    email: "o.smirnova@nhtk.local",
    phone: "+7 8555 31-41-77",
    initials: "СО",
    hired: "2017-01-16",
    profession: "Кладовщик",
  },
  {
    id: "u9",
    name: "Кузнецов Андрей Михайлович",
    shortName: "Кузнецов А.",
    role: "employee",
    position: "Мастер цеха",
    department: "Производство полимеров",
    site: "Площадка «Центральная»",
    workshop: "Цех полимеров №1",
    birthday: "05-28",
    email: "a.kuznetsov@nhtk.local",
    phone: "+7 8555 31-44-10",
    initials: "КА",
    hired: "2009-08-03",
    profession: "Мастер",
  },
  {
    id: "u10",
    name: "Федорова Наталья Владимировна",
    shortName: "Федорова Н.",
    role: "trainer",
    position: "Специалист по обучению",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Центральная»",
    workshop: "Административный корпус",
    birthday: "09-12",
    email: "n.fedorova@nhtk.local",
    phone: "+7 8555 31-20-25",
    initials: "ФН",
    hired: "2021-03-01",
    profession: "Методист",
  },
  {
    id: "u11",
    name: "Орлов Виктор Степанович",
    shortName: "Орлов В.",
    role: "specialist",
    position: "Ведущий аудитор HSE",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Восточная»",
    workshop: "Установка пиролиза",
    birthday: "02-25",
    email: "v.orlov@nhtk.local",
    phone: "+7 8555 31-62-33",
    initials: "ОВ",
    hired: "2013-10-07",
    profession: "Аудитор",
  },
  {
    id: "u12",
    name: "Белова Татьяна Олеговна",
    shortName: "Белова Т.",
    role: "employee",
    position: "Документовед ОТ",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Центральная»",
    workshop: "Административный корпус",
    birthday: "07-19",
    email: "t.belova@nhtk.local",
    phone: "+7 8555 31-20-18",
    initials: "БТ",
    hired: "2022-06-06",
    profession: "Документовед",
  },
  {
    id: "u13",
    name: "Григорьев Максим Иванович",
    shortName: "Григорьев М.",
    role: "employee",
    position: "Оператор технологических установок",
    department: "Производство мономеров",
    site: "Площадка «Восточная»",
    workshop: "Цех мономеров",
    birthday: "10-30",
    email: "m.grigoriev@nhtk.local",
    phone: "+7 8555 31-63-14",
    initials: "ГМ",
    hired: "2015-12-01",
    profession: "Оператор",
  },
  {
    id: "u14",
    name: "Павлова Ирина Дмитриевна",
    shortName: "Павлова И.",
    role: "specialist",
    position: "Инженер промышленной безопасности",
    department: "Департамент ОТ, ПБиЭ",
    site: "Площадка «Северная»",
    workshop: "Компрессорная станция",
    birthday: "03-08",
    email: "i.pavlova@nhtk.local",
    phone: "+7 8555 31-70-05",
    initials: "ПИ",
    hired: "2016-09-12",
    profession: "Инженер ПБ",
  },
];

export function createSeed(): AppState {
  return {
    users,
    currentUserId: "u1",
    favorites: ["d1", "d4"],
    policyVersion: "5.1",
    champSeason: "Сезон 2026 — «Территория безопасности»",
    champRules:
      "Баллы начисляются командам цехов за контакты по безопасности, устранение нарушений и квизы. Подтверждает внутренний тренер или специалист ОТ. Фото и комментарий обязательны. Спорные баллы рассматривает комиссия HSE в течение 3 рабочих дней.",
    incidents: [
      {
        id: "inc1",
        number: "НХТК-2025-047",
        datetime: isoDays(-236, 14, 20),
        site: "Площадка «Центральная»",
        workshop: "Цех полимеров №1",
        place: "Насос Н-1204, отм. +6.000",
        type: "с потерей времени",
        severity: "высокая",
        injured: ["Петров Сергей Николаевич"],
        description:
          "Аппаратчик поскользнулся на масляном пятне у насоса Н-1204, получил растяжение связок голеностопа. Потеря трудоспособности 11 дней.",
        causes: [
          "Поскользнулся на масле у насоса",
          "Утечка с торцевого уплотнения Н-1204",
          "Дефект в журнале не закрыт 9 суток",
          "Запчасть не заказана в МТО",
          "Нет контроля исполнения заявок на уплотнения",
        ],
        witnesses: ["Кузнецов А.М.", "Григорьев М.И."],
        attachments: ["акт_Н-1204.pdf", "фото_пятно.jpg"],
        status: "закрыто",
        owner: "u1",
        due: isoDateOnly(-200),
        confirmed: true,
        relatedAuditIds: ["a2"],
        capa: [
          { id: "c1", task: "Замена торцевого уплотнения Н-1204", owner: "Кузнецов А.М.", due: isoDateOnly(-210), status: "закрыто" },
          { id: "c2", task: "Антискользящее покрытие зоны насосов", owner: "Новиков А.П.", due: isoDateOnly(-190), status: "закрыто" },
        ],
      },
      {
        id: "inc2",
        number: "НХТК-2026-004",
        datetime: isoDays(-18, 9, 40),
        site: "Площадка «Восточная»",
        workshop: "Установка пиролиза",
        place: "Печь П-101, площадка горелок",
        type: "почти-событие",
        severity: "средняя",
        injured: [],
        description: "При обходе обнаружено ослабление фланцевого соединения на линии топливного газа. Утечки не было, соединение подтянуто.",
        causes: ["Ослабление шпилек после термоцикла", "Не выполнен контроль момента затяжки после ППР"],
        witnesses: ["Новиков А.П."],
        attachments: ["фото_фланец.jpg"],
        status: "меры",
        owner: "u11",
        due: isoDateOnly(7),
        confirmed: true,
        relatedAuditIds: ["a1"],
        capa: [{ id: "c3", task: "Регламент контроля затяжки после ППР", owner: "Павлова И.Д.", due: isoDateOnly(10), status: "в работе" }],
      },
      {
        id: "inc3",
        number: "НХТК-2026-007",
        datetime: isoDays(-9, 16, 5),
        site: "Площадка «Северная»",
        workshop: "Очистные сооружения",
        place: "Пруд-накопитель №2",
        type: "экологический инцидент",
        severity: "средняя",
        injured: [],
        description: "Кратковременное превышение ХПК в контрольной точке К-4. Сброс остановлен, лаборатория подтвердила возврат к норме через 4 часа.",
        causes: ["Перегрузка аэротенка", "Несвоевременный вывод избыточного ила"],
        witnesses: ["Волкова М.А."],
        attachments: ["протокол_лаб.pdf"],
        status: "расследование",
        owner: "u6",
        due: isoDateOnly(5),
        confirmed: true,
        relatedAuditIds: [],
        capa: [{ id: "c4", task: "График вывода ила и датчик нагрузки", owner: "Волкова М.А.", due: isoDateOnly(12), status: "открыто" }],
      },
      {
        id: "inc4",
        number: "НХТК-2026-009",
        datetime: isoDays(-4, 11, 12),
        site: "Площадка «Центральная»",
        workshop: "Ремонтно-механический цех",
        place: "Участок токарный",
        type: "микротравма",
        severity: "низкая",
        injured: ["Григорьев Максим Иванович"],
        description: "Ссадина кисти при снятии заусенца без рукавиц. Обработано в медпункте, работа продолжена.",
        causes: ["Не использованы рукавицы", "Спешка перед сдачей смены"],
        witnesses: [],
        attachments: [],
        status: "закрыто",
        owner: "u1",
        due: isoDateOnly(-1),
        confirmed: true,
        relatedAuditIds: [],
        capa: [{ id: "c5", task: "Внеплановый инструктаж по СИЗ на участке", owner: "Козлов Д.П.", due: isoDateOnly(-2), status: "закрыто" }],
      },
      {
        id: "inc5",
        number: "НХТК-2026-011",
        datetime: isoDays(-2, 8, 15),
        site: "Площадка «Восточная»",
        workshop: "Цех мономеров",
        place: "Компрессор К-12",
        type: "без потери времени",
        severity: "низкая",
        injured: ["Кузнецов Андрей Михайлович"],
        description: "Ушиб плеча о ограждение при обходе. Боль прошла, освобождения от работы не требовалось.",
        causes: ["Узкий проход", "Временное складирование деталей в проходе"],
        witnesses: ["Новиков А.П."],
        attachments: ["фото_проход.jpg"],
        status: "меры",
        owner: "u1",
        due: isoDateOnly(3),
        confirmed: true,
        relatedAuditIds: [],
        capa: [{ id: "c6", task: "Разметка зон складирования и барьер", owner: "Кузнецов А.М.", due: isoDateOnly(4), status: "в работе" }],
      },
      {
        id: "inc6",
        number: "НХТК-2026-012",
        datetime: isoDays(-1, 19, 40),
        site: "Площадка «Центральная»",
        workshop: "Склад ГСМ",
        place: "Резервуар Р-3",
        type: "пожар",
        severity: "критическая",
        injured: [],
        description: "Черновик: запах гари у дыхательного клапана Р-3. Требуется подтверждение и классификация.",
        causes: [],
        witnesses: ["Смирнова О.И."],
        attachments: [],
        status: "черновик",
        owner: "u1",
        due: isoDateOnly(2),
        confirmed: false,
        relatedAuditIds: [],
        capa: [],
      },
    ],
    contacts: [
      {
        id: "sc1",
        date: isoDateOnly(-3),
        shift: "Смена А",
        workshop: "Цех полимеров №1",
        topic: "Блокировка энергии перед вскрытием насоса",
        participants: ["Петров С.Н.", "Кузнецов А.М."],
        observations: "Слесарь начал работу без проверки LOTO. Остановлен мастером.",
        photo: "auditWalk",
        risk: "средний",
        measures: "Повторный целевой инструктаж, проверка бирок на щите.",
        authorId: "u9",
        createdAt: isoDays(-3, 15),
      },
      {
        id: "sc2",
        date: isoDateOnly(-1),
        shift: "Смена Б",
        workshop: "Установка пиролиза",
        topic: "Работа на высоте — страховка",
        participants: ["Новиков А.П.", "подряд ООО «Вершина»"],
        observations: "Страховочный строп закреплён за технологическую линию, а не за анкер.",
        photo: "safetyTeam",
        risk: "высокий",
        measures: "Работы остановлены, анкерная точка указана, допуск подрядчика ограничен.",
        authorId: "u7",
        createdAt: isoDays(-1, 11),
      },
      {
        id: "sc3",
        date: isoDateOnly(0),
        shift: "Дневная",
        workshop: "Очистные сооружения",
        topic: "СИЗ органов дыхания у аэротенков",
        participants: ["Волкова М.А.", "Григорьев М.И."],
        observations: "Респираторы используются, запас картриджей на месте.",
        risk: "низкий",
        measures: "Положительная практика, рекомендовано к чемпионату.",
        authorId: "u6",
        createdAt: isoDays(0, 9, 20),
      },
    ],
    documents: [
      {
        id: "d1",
        title: "Политика в области ОТ, ПБ, БДиООС",
        kind: "политика",
        folder: "политики",
        version: "5.1",
        date: isoDateOnly(-80),
        owner: "Соколова Е.В.",
        site: "Все площадки",
        file: "Политика_ОТ_ПБ_БДиООС_v5.1.pdf",
        status: "действует",
        tags: ["политика", "обязательно"],
        body: "НХТК считает жизнь и здоровье людей абсолютным приоритетом. Никакие производственные показатели не могут быть важнее безопасного выполнения работы.",
        versions: [
          { version: "5.1", date: isoDateOnly(-80), author: "Соколова Е.В.", note: "Актуализация целей 2026" },
          { version: "5.0", date: isoDateOnly(-430), author: "Соколова Е.В.", note: "Новая редакция" },
        ],
      },
      {
        id: "d2",
        title: "Стандарт «Расследование происшествий»",
        kind: "стандарт",
        folder: "стандарты",
        version: "3.4",
        date: isoDateOnly(-120),
        owner: "Иванова А.С.",
        site: "Все площадки",
        file: "СТ-ОТ-03-Расследование.pdf",
        status: "действует",
        tags: ["происшествия", "5why"],
        body: "Все происшествия, включая почти-события, регистрируются в течение смены. Расследование LTI — комиссия под председательством руководителя площадки.",
        versions: [{ version: "3.4", date: isoDateOnly(-120), author: "Иванова А.С.", note: "Добавлен тип экологический инцидент" }],
      },
      {
        id: "d3",
        title: "Инструкция по газоопасным работам",
        kind: "инструкция",
        folder: "инструкции",
        version: "12.0",
        date: isoDateOnly(-40),
        owner: "Павлова И.Д.",
        site: "Площадка «Восточная»",
        file: "И-ПБ-12-ГОР.pdf",
        status: "действует",
        tags: ["наряд-допуск", "ГОР"],
        body: "Газоопасные работы выполняются только по наряду-допуску с анализом воздушной среды.",
        versions: [{ version: "12.0", date: isoDateOnly(-40), author: "Павлова И.Д.", note: "Согласовано с Ростехнадзором" }],
      },
      {
        id: "d4",
        title: "Шаблон акта-допуска подрядчика",
        kind: "шаблон",
        folder: "шаблоны актов/нарядов",
        version: "2.1",
        date: isoDateOnly(-15),
        owner: "Белова Т.О.",
        site: "Все площадки",
        file: "Шаблон_акт_допуска.docx",
        status: "действует",
        tags: ["подрядчик", "шаблон"],
        body: "Заполняется до начала работ. Приложения: СИЗ, обучение, страховка, наряд.",
        versions: [{ version: "2.1", date: isoDateOnly(-15), author: "Белова Т.О.", note: "Поля ИНН и ОПО" }],
      },
      {
        id: "d5",
        title: "Чек-лист поведенческого аудита (BBS)",
        kind: "чек-лист",
        folder: "чек-листы",
        version: "1.6",
        date: isoDateOnly(-25),
        owner: "Орлов В.С.",
        site: "Все площадки",
        file: "BBS_checklist.xlsx",
        status: "действует",
        tags: ["аудит", "BBS"],
        body: "Наблюдение за людьми, а не за оборудованием. Минимум 15 минут, обратная связь на месте.",
        versions: [{ version: "1.6", date: isoDateOnly(-25), author: "Орлов В.С.", note: "Добавлен блок подрядчики" }],
      },
      {
        id: "d6",
        title: "База знаний: типовые причины падений",
        kind: "база знаний",
        folder: "база знаний",
        version: "1.0",
        date: isoDateOnly(-60),
        owner: "Козлов Д.П.",
        site: "Все площадки",
        file: "KB_falls.pdf",
        status: "действует",
        tags: ["знания", "падения"],
        body: "Разливы, временные кабели, неочищенный снег на эстакадах, отсутствие поручней.",
        versions: [{ version: "1.0", date: isoDateOnly(-60), author: "Козлов Д.П.", note: "Первая публикация" }],
      },
      {
        id: "d7",
        title: "Инструкция по работам на высоте",
        kind: "инструкция",
        folder: "инструкции",
        version: "8.2",
        date: isoDateOnly(-400),
        owner: "Иванова А.С.",
        site: "Все площадки",
        file: "И-ОТ-08-Высота.pdf",
        status: "архив",
        tags: ["высота", "архив"],
        body: "Архивная редакция. Действует версия 9.0 на бумажном согласовании.",
        versions: [{ version: "8.2", date: isoDateOnly(-400), author: "Иванова А.С.", note: "Заменена" }],
      },
      {
        id: "d8",
        title: "Стандарт выдачи СИЗ",
        kind: "стандарт",
        folder: "стандарты",
        version: "4.0",
        date: isoDateOnly(-90),
        owner: "Смирнова О.И.",
        site: "Все площадки",
        file: "СТ-СИЗ-04.pdf",
        status: "действует",
        tags: ["СИЗ", "нормы"],
        body: "Нормы выдачи по профессиям, сроки замены, порядок заявки через портал.",
        versions: [{ version: "4.0", date: isoDateOnly(-90), author: "Смирнова О.И.", note: "Переход на портальные заявки" }],
      },
    ],
    acknowledgements: [
      { id: "ack1", docId: "d1", userId: "u2", date: isoDays(-20) },
      { id: "ack2", docId: "d1", userId: "u9", date: isoDays(-18) },
      { id: "ack3", docId: "d3", userId: "u7", date: isoDays(-10) },
    ],
    ppe: [
      { id: "p1", name: "Каска защитная", sku: "СИЗ-КС-01", category: "голова", unit: "шт", stock: 140, minStock: 40, lifeMonths: 36, sizes: ["универсальный"] },
      { id: "p2", name: "Очки закрытые", sku: "СИЗ-ОЧ-04", category: "зрение", unit: "шт", stock: 86, minStock: 30, lifeMonths: 12, sizes: ["универсальный"] },
      { id: "p3", name: "Противогаз ППФ", sku: "СИЗ-ПГ-11", category: "дыхание", unit: "шт", stock: 24, minStock: 20, lifeMonths: 24, sizes: ["2", "3", "4"] },
      { id: "p4", name: "Перчатки кислотостойкие", sku: "СИЗ-ПР-22", category: "руки", unit: "пар", stock: 310, minStock: 80, lifeMonths: 3, sizes: ["8", "9", "10", "11"] },
      { id: "p5", name: "Ботинки маслобензостойкие", sku: "СИЗ-ОБ-07", category: "ноги", unit: "пар", stock: 18, minStock: 25, lifeMonths: 12, sizes: ["41", "42", "43", "44", "45"] },
      { id: "p6", name: "Наушники противошумные", sku: "СИЗ-НС-03", category: "слух", unit: "шт", stock: 54, minStock: 20, lifeMonths: 24, sizes: ["универсальный"] },
      { id: "p7", name: "Жилет сигнальный", sku: "СИЗ-ЖС-01", category: "видимость", unit: "шт", stock: 200, minStock: 50, lifeMonths: 24, sizes: ["M", "L", "XL", "XXL"] },
      { id: "p8", name: "Костюм кислотозащитный", sku: "СИЗ-КК-09", category: "тело", unit: "шт", stock: 12, minStock: 10, lifeMonths: 18, sizes: ["48-50", "52-54", "56-58"] },
    ],
    ppeNorms: [
      { id: "n1", profession: "Аппаратчик", itemId: "p1", qty: 1, periodMonths: 24 },
      { id: "n2", profession: "Аппаратчик", itemId: "p4", qty: 12, periodMonths: 12 },
      { id: "n3", profession: "Аппаратчик", itemId: "p5", qty: 1, periodMonths: 12 },
      { id: "n4", profession: "Оператор", itemId: "p3", qty: 1, periodMonths: 24 },
      { id: "n5", profession: "Мастер", itemId: "p7", qty: 1, periodMonths: 24 },
      { id: "n6", profession: "Кладовщик", itemId: "p2", qty: 1, periodMonths: 12 },
    ],
    ppeRequests: [
      { id: "pr1", date: isoDateOnly(-6), userId: "u2", itemId: "p5", size: "43", qty: 1, status: "выдана", comment: "Износ подошвы" },
      { id: "pr2", date: isoDateOnly(-1), userId: "u13", itemId: "p3", size: "3", qty: 1, status: "одобрена", comment: "Истекает срок" },
      { id: "pr3", date: isoDateOnly(0), userId: "u9", itemId: "p8", size: "52-54", qty: 1, status: "новая", comment: "ППР на кислотной линии" },
    ],
    risks: [
      { id: "r1", hazard: "Падение на скользкой поверхности", workplace: "Насосная Н-12", workshop: "Цех полимеров №1", probability: 3, severity: 4, measures: "Покрытие, разметка, контроль утечек", residual: 6, owner: "Кузнецов А.М." },
      { id: "r2", hazard: "Отравление парами углеводородов", workplace: "Печь П-101", workshop: "Установка пиролиза", probability: 2, severity: 5, measures: "Газоанализаторы, противогазы, наряд", residual: 6, owner: "Новиков А.П." },
      { id: "r3", hazard: "Шум выше ПДУ", workplace: "Компрессор К-12", workshop: "Цех мономеров", probability: 5, severity: 2, measures: "Наушники, кожухи, ротация", residual: 6, owner: "Павлова И.Д." },
      { id: "r4", hazard: "Падение с высоты", workplace: "Эстакада налива", workshop: "Эстакада налива", probability: 2, severity: 5, measures: "Анкерные линии, страховка, допуск", residual: 8, owner: "Иванова А.С." },
      { id: "r5", hazard: "Химический ожог", workplace: "Участок реагентов", workshop: "Очистные сооружения", probability: 2, severity: 4, measures: "Костюм КЩ, душ, инструктаж", residual: 4, owner: "Волкова М.А." },
    ],
    sout: [
      { id: "s1", workplace: "Аппаратчик полимеризации", workshop: "Цех полимеров №1", class: "3.1", validUntil: isoDateOnly(220), factors: ["шум", "хим. фактор"], guarantees: ["молоко", "доп. отпуск 7 дн."], file: "СОУТ_П-14.pdf" },
      { id: "s2", workplace: "Оператор пиролиза", workshop: "Установка пиролиза", class: "3.2", validUntil: isoDateOnly(40), factors: ["шум", "тепло", "углеводороды"], guarantees: ["сокращённый день", "доплата 12%"], file: "СОУТ_ПИР-02.pdf" },
      { id: "s3", workplace: "Инженер ОТ", workshop: "Административный корпус", class: "2", validUntil: isoDateOnly(400), factors: [], guarantees: [], file: "СОУТ_АДМ.pdf" },
      { id: "s4", workplace: "Слесарь-ремонтник", workshop: "Ремонтно-механический цех", class: "3.1", validUntil: isoDateOnly(-5), factors: ["шум", "вибрация", "пыль"], guarantees: ["молоко", "медосмотр 1 раз/год"], file: "СОУТ_РМЦ.pdf" },
    ],
    courses: [
      {
        id: "cr1",
        title: "Охрана труда для рабочих",
        category: "ОТ",
        program: "Основные опасности НХТК, права работника, действия при аварии, СИЗ.",
        hours: 16,
        format: "смешанный",
        validityMonths: 12,
        questions: [
          { q: "Что важнее производственного плана?", options: ["Выполнение нормы", "Жизнь и здоровье", "Срок ремонта", "KPI смены"], answer: 1 },
          { q: "Когда можно снять каску на установке?", options: ["В жару", "Никогда в рабочей зоне", "Если нет людей", "На обеде в бытовке — да, на установке — нет"], answer: 3 },
          { q: "Почти-событие нужно регистрировать?", options: ["Нет", "Только LTI", "Да, всегда", "Только по указанию мастера"], answer: 2 },
          { q: "Кто вправе остановить опасную работу?", options: ["Только начальник", "Любой работник", "Только ОТ", "Только подрядчик"], answer: 1 },
        ],
      },
      {
        id: "cr2",
        title: "ПБ опасных производственных объектов",
        category: "ПБ",
        program: "ОПО НХТК, лицензии, ПЛАС, наряды-допуски, экспертиза.",
        hours: 24,
        format: "очно",
        validityMonths: 12,
        questions: [
          { q: "ПЛАС — это?", options: ["План ликвидации аварийных ситуаций", "Паспорт лабораторного анализа", "Приказ о льготах"], answer: 0 },
          { q: "Газоопасные работы без наряда?", options: ["Можно в дневную смену", "Запрещены", "Можно при мастере"], answer: 1 },
        ],
      },
      {
        id: "cr3",
        title: "Первая помощь",
        category: "первая помощь",
        program: "Алгоритм вызова медслужбы, кровотечение, ожог, реанимация.",
        hours: 8,
        format: "очно",
        validityMonths: 12,
        questions: [
          { q: "Первое действие при сильном кровотечении?", options: ["Ждать врача", "Прямое давление на рану", "Вода"], answer: 1 },
        ],
      },
      {
        id: "cr4",
        title: "Работы на высоте",
        category: "высоты",
        program: "Анкерные точки, стропы, люльки, запрет на закрепление за трубы.",
        hours: 16,
        format: "смешанный",
        validityMonths: 12,
        questions: [],
      },
      {
        id: "cr5",
        title: "Сосуды под давлением",
        category: "сосуды",
        program: "Паспорт сосуда, клапаны, экспертиза, запрет заглушек на предохранителях.",
        hours: 20,
        format: "электронно",
        validityMonths: 36,
        questions: [],
      },
      {
        id: "cr6",
        title: "Экология для линейных руководителей",
        category: "экология",
        program: "Сбросы, выбросы, отходы I–V классов, журнал ППЗ смежно.",
        hours: 8,
        format: "электронно",
        validityMonths: 24,
        questions: [],
      },
    ],
    enrollments: [
      { id: "e1", courseId: "cr1", userId: "u2", assignedAt: isoDays(-40), progress: 100, score: 100, completedAt: isoDays(-30), certificateNo: "НХТК-ОТ-2025-118", expiresAt: isoDateOnly(335) },
      { id: "e2", courseId: "cr2", userId: "u7", assignedAt: isoDays(-20), progress: 60 },
      { id: "e3", courseId: "cr3", userId: "u9", assignedAt: isoDays(-200), progress: 100, score: 80, completedAt: isoDays(-190), certificateNo: "НХТК-ПП-2025-044", expiresAt: isoDateOnly(-10) },
      { id: "e4", courseId: "cr1", userId: "u13", assignedAt: isoDays(-5), progress: 20 },
      { id: "e5", courseId: "cr4", userId: "u2", assignedAt: isoDays(-2), progress: 0 },
    ],
    briefings: [
      {
        id: "b1",
        date: isoDateOnly(-30),
        type: "повторный",
        program: "Повторный инструктаж по ОТ, цех полимеров",
        instructor: "Кузнецов А.М.",
        workers: [{ userId: "u2", signed: true }, { userId: "u9", signed: true }],
        attachments: ["журнал_п1.pdf"],
        workshop: "Цех полимеров №1",
        nextDate: isoDateOnly(60),
      },
      {
        id: "b2",
        date: isoDateOnly(-200),
        type: "первичный",
        program: "Первичный на рабочем месте — оператор",
        instructor: "Новиков А.П.",
        workers: [{ userId: "u13", signed: true }],
        attachments: [],
        workshop: "Цех мономеров",
        nextDate: isoDateOnly(-20),
      },
      {
        id: "b3",
        date: isoDateOnly(-4),
        type: "целевой",
        program: "Целевой: огневые работы на эстакаде",
        instructor: "Иванова А.С.",
        workers: [{ userId: "u7", signed: true }, { userId: "u13", signed: false }],
        attachments: ["наряд_ОВ-19.pdf"],
        workshop: "Эстакада налива",
        nextDate: isoDateOnly(3),
      },
      {
        id: "b4",
        date: isoDateOnly(-1),
        type: "внеплановый",
        program: "Внеплановый по микротравме в РМЦ",
        instructor: "Козлов Д.П.",
        workers: [{ userId: "u13", signed: true }, { userId: "u9", signed: true }],
        attachments: [],
        workshop: "Ремонтно-механический цех",
      },
      {
        id: "b5",
        date: isoDateOnly(-10),
        type: "вводный",
        program: "Вводный инструктаж для подрядчика «Вершина»",
        instructor: "Федорова Н.В.",
        workers: [{ userId: "u3", signed: true }],
        attachments: ["вводный_Вершина.pdf"],
        workshop: "Административный корпус",
        nextDate: isoDateOnly(80),
      },
    ],
    champTeams: [
      { id: "t1", name: "Полимер", workshop: "Цех полимеров №1", members: ["u2", "u9"] },
      { id: "t2", name: "Пиролиз", workshop: "Установка пиролиза", members: ["u7"] },
      { id: "t3", name: "Мономеры", workshop: "Цех мономеров", members: ["u13"] },
      { id: "t4", name: "РМЦ", workshop: "Ремонтно-механический цех", members: ["u11"] },
      { id: "t5", name: "Штаб", workshop: "Административный корпус", members: ["u12", "u10"] },
    ],
    champTasks: [
      { id: "ct1", title: "Контакт по безопасности", points: 10, description: "Проведите и зафиксируйте контакт с фото.", type: "контакт" },
      { id: "ct2", title: "Устранение нарушения", points: 15, description: "Закройте найденное нарушение в течение смены.", type: "нарушение" },
      { id: "ct3", title: "Квиз недели", points: 8, description: "Командный квиз по ЛНА.", type: "квиз" },
      { id: "ct4", title: "Обход руководителя", points: 12, description: "Совместный обход с фиксацией практик.", type: "обход" },
    ],
    champSubmissions: [
      { id: "cs1", teamId: "t1", taskId: "ct1", userId: "u9", comment: "LOTO у насоса Н-1204", photo: "auditWalk", points: 10, status: "подтверждено", date: isoDays(-3) },
      { id: "cs2", teamId: "t2", taskId: "ct2", userId: "u7", comment: "Убрали строп с линии, поставили анкер", photo: "safetyTeam", points: 15, status: "подтверждено", date: isoDays(-1) },
      { id: "cs3", teamId: "t3", taskId: "ct3", userId: "u13", comment: "Квиз пройден 7/8", points: 8, status: "на проверке", date: isoDays(0, 8) },
      { id: "cs4", teamId: "t4", taskId: "ct1", userId: "u11", comment: "Контакт по рукавицам на токарном", points: 10, status: "отклонено", date: isoDays(-2) },
    ],
    champNews: [
      { id: "cn1", date: isoDays(-6), title: "Старт этапа «Весна 2026»", text: "Этап длится до конца марта. Фокус — работы на высоте и LOTO." },
      { id: "cn2", date: isoDays(-1), title: "Пиролиз вышел в лидеры", text: "Команда установки пиролиза получила 15 баллов за остановку небезопасной работы подрядчика." },
    ],
    contractors: [
      {
        id: "k1",
        name: "ООО «Вершина-Сервис»",
        inn: "1650123456",
        contract: "Д-2026-014",
        workType: "Работы на высоте, изоляция",
        siteAccess: "Площадка «Восточная»",
        owner: "Новиков А.П.",
        status: "ограничен",
        rating: 3.4,
        docs: [
          { name: "Наряд-допуск", validUntil: isoDateOnly(12), ok: true },
          { name: "Обучение высоте", validUntil: isoDateOnly(40), ok: true },
          { name: "Страховка", validUntil: isoDateOnly(-2), ok: false },
        ],
        violations: [{ date: isoDateOnly(-1), text: "Строп за технологическую линию", severity: "высокая" }],
      },
      {
        id: "k2",
        name: "АО «ПромМонтаж»",
        inn: "1650987654",
        contract: "Д-2025-088",
        workType: "ППР насосного оборудования",
        siteAccess: "Площадка «Центральная»",
        owner: "Кузнецов А.М.",
        status: "допущен",
        rating: 4.6,
        docs: [
          { name: "Наряд-допуск", validUntil: isoDateOnly(20), ok: true },
          { name: "СИЗ", validUntil: isoDateOnly(90), ok: true },
          { name: "Обучение ОТ", validUntil: isoDateOnly(120), ok: true },
          { name: "Страховка", validUntil: isoDateOnly(200), ok: true },
        ],
        violations: [],
      },
      {
        id: "k3",
        name: "ООО «ЭкоТранс»",
        inn: "1650555123",
        contract: "Д-2026-003",
        workType: "Вывоз отходов I–III классов",
        siteAccess: "Площадка «Северная»",
        owner: "Волкова М.А.",
        status: "допущен",
        rating: 4.2,
        docs: [
          { name: "Лицензия на отходы", validUntil: isoDateOnly(300), ok: true },
          { name: "Страховка", validUntil: isoDateOnly(60), ok: true },
        ],
        violations: [{ date: isoDateOnly(-40), text: "Опоздание к шлюзу на 40 мин", severity: "низкая" }],
      },
      {
        id: "k4",
        name: "ИП Белов Р.С.",
        inn: "1657001122",
        contract: "Д-2024-199",
        workType: "Уборка территории",
        siteAccess: "Все площадки",
        owner: "Смирнова О.И.",
        status: "заблокирован",
        rating: 2.1,
        docs: [{ name: "Обучение ОТ", validUntil: isoDateOnly(-30), ok: false }],
        violations: [{ date: isoDateOnly(-30), text: "Работа без вводного инструктажа", severity: "высокая" }],
      },
    ],
    trainers: [
      { id: "tr1", userId: "u3", competencies: ["ОТ", "первая помощь", "высота", "чемпионат"], hours: 186, coverage: 412, rating: 4.8, materials: ["Презентация LOTO.pptx", "Макет наряда.docx"] },
      { id: "tr2", userId: "u10", competencies: ["вводный", "экология", "методики"], hours: 94, coverage: 220, rating: 4.6, materials: ["Вводный_2026.pdf"] },
    ],
    sessions: [
      { id: "se1", trainerId: "tr1", title: "Первая помощь, группа смены А", date: isoDateOnly(2), time: "09:00", place: "Учебный класс 2", group: "Смена А / полимеры", relatedCourseId: "cr3" },
      { id: "se2", trainerId: "tr1", title: "Квиз чемпионата — высота", date: isoDateOnly(5), time: "14:00", place: "Актовый зал", group: "Все команды", relatedCourseId: "cr4" },
      { id: "se3", trainerId: "tr2", title: "Вводный для подрядчиков", date: isoDateOnly(1), time: "08:30", place: "КПП-2", group: "Подрядчики" },
      { id: "se4", trainerId: "tr1", title: "ПБ ОПО, пиролиз", date: isoDateOnly(-2), time: "10:00", place: "Операторная пиролиза", group: "Установка пиролиза", relatedCourseId: "cr2" },
    ],
    trainerApps: [
      { id: "ta1", userId: "u9", motivation: "Хочу вести инструктажи на своём участке и развивать BBS.", date: isoDateOnly(-8), status: "новая" },
    ],
    audits: [
      {
        id: "a1",
        type: "поведенческий",
        date: isoDateOnly(-5),
        site: "Площадка «Восточная»",
        workshop: "Установка пиролиза",
        auditor: "Орлов В.С.",
        status: "проведён",
        checklist: [
          { item: "СИЗ используются правильно", ok: true },
          { item: "Порядок на рабочем месте", ok: false },
          { item: "Блокировка энергии", ok: true },
          { item: "Коммуникация в бригаде", ok: true },
        ],
        findings: [
          { id: "f1", text: "Временные детали в проходе у К-12", result: "несоответствие", criticality: "средняя", photo: "auditWalk", taskId: "tk1" },
          { id: "f2", text: "Каски и очки надеты у всей смены", result: "соответствует", criticality: "низкая" },
        ],
      },
      {
        id: "a2",
        type: "внутренний",
        date: isoDateOnly(-12),
        site: "Площадка «Центральная»",
        workshop: "Цех полимеров №1",
        auditor: "Иванова А.С.",
        status: "закрыт",
        checklist: [
          { item: "Журнал дефектов ведётся", ok: true },
          { item: "Аптечка укомплектована", ok: true },
        ],
        findings: [{ id: "f3", text: "Антискользящее покрытие нанесено", result: "соответствует", criticality: "низкая" }],
      },
      {
        id: "a3",
        type: "обход руководителя",
        date: isoDateOnly(3),
        site: "Площадка «Северная»",
        workshop: "Очистные сооружения",
        auditor: "Соколова Е.В.",
        status: "план",
        checklist: [
          { item: "Сбросы в норме", ok: false },
          { item: "Журнал ПЭК", ok: false },
        ],
        findings: [],
      },
      {
        id: "a4",
        type: "аудит подрядчика",
        date: isoDateOnly(-1),
        site: "Площадка «Восточная»",
        workshop: "Установка пиролиза",
        auditor: "Орлов В.С.",
        status: "проведён",
        checklist: [
          { item: "Вводный пройден", ok: true },
          { item: "Страховка действительна", ok: false },
          { item: "СИЗ подрядчика", ok: true },
        ],
        findings: [{ id: "f4", text: "Страховка «Вершина-Сервис» истекла", result: "несоответствие", criticality: "высокая", taskId: "tk2" }],
      },
    ],
    tasks: [
      { id: "tk1", title: "Убрать складирование в проходе К-12", description: "По находке аудита a1. Разметить зону.", owner: "Кузнецов А.М.", due: isoDateOnly(2), status: "в работе", source: "аудит", sourceId: "a1", verified: false },
      { id: "tk2", title: "Приостановить допуск «Вершина» до страховки", description: "Ограничить статус подрядчика.", owner: "Иванова А.С.", due: isoDateOnly(-1), status: "просрочено", source: "аудит", sourceId: "a4", verified: false },
      { id: "tk3", title: "Регламент затяжки фланцев после ППР", description: "Связано с почти-событием НХТК-2026-004", owner: "Павлова И.Д.", due: isoDateOnly(10), status: "в работе", source: "происшествие", sourceId: "inc2", verified: false },
      { id: "tk4", title: "Внеплановый инструктаж РМЦ", description: "По микротравме", owner: "Козлов Д.П.", due: isoDateOnly(-2), status: "закрыто", source: "происшествие", sourceId: "inc4", verified: true },
      { id: "tk5", title: "Подготовить пакет к проверке Ростехнадзора", description: "ПЛАС, экспертизы, журналы", owner: "Павлова И.Д.", due: isoDateOnly(8), status: "новые", source: "надзор", sourceId: "insp1", verified: false },
    ],
    generalDocs: [
      { id: "g1", title: "Приказ о старте чемпионата 2026", folder: "приказы", date: isoDateOnly(-20), owner: "Соколова Е.В.", file: "Приказ_ЧБ_2026.pdf", downloadable: true },
      { id: "g2", title: "Объявление: медосмотр март", folder: "объявления", date: isoDateOnly(-4), owner: "Федорова Н.В.", file: "Медосмотр_март.pdf", downloadable: true },
      { id: "g3", title: "Шаблон служебной записки HSE", folder: "шаблоны писем", date: isoDateOnly(-90), owner: "Белова Т.О.", file: "СЗ_шаблон.docx", downloadable: true },
      { id: "g4", title: "Оргструктура департамента ОТ, ПБиЭ", folder: "оргструктура", date: isoDateOnly(-50), owner: "Соколова Е.В.", file: "Оргструктура.pdf", downloadable: true },
      { id: "g5", title: "Контакты HSE и экстренных служб", folder: "контакты", date: isoDateOnly(-10), owner: "Иванова А.С.", file: "Контакты.pdf", downloadable: true },
    ],
    fire: [
      { id: "fi1", type: "АПС", inventory: "АПС-Ц-01", place: "Цех полимеров №1, щитовая", lastTo: isoDateOnly(-40), nextTo: isoDateOnly(20), notes: "Без замечаний", acts: ["Акт ТО 02.2026"] },
      { id: "fi2", type: "АУПТ", inventory: "АУПТ-П-02", place: "Склад ГСМ, насосная", lastTo: isoDateOnly(-80), nextTo: isoDateOnly(-3), notes: "Требуется промывка оросителей", acts: ["Акт ТО 12.2025"] },
      { id: "fi3", type: "огнетушитель", inventory: "ОП-10-118", place: "Операторная пиролиза", lastTo: isoDateOnly(-15), nextTo: isoDateOnly(70), notes: "Давление в норме", acts: [] },
      { id: "fi4", type: "гидрант", inventory: "ПГ-С-07", place: "Очистные, кольцо №2", lastTo: isoDateOnly(-100), nextTo: isoDateOnly(10), notes: "Крышка окрашена", acts: ["Протокол водоотдачи"] },
      { id: "fi5", type: "противопожарная дверь", inventory: "ПД-А-03", place: "Адм. корпус, архив ЛНА", lastTo: isoDateOnly(-200), nextTo: isoDateOnly(-12), notes: "Доводчик ослаблен", acts: [] },
      { id: "fi6", type: "огнетушитель", inventory: "ОП-5-044", place: "РМЦ, токарный", lastTo: isoDateOnly(-5), nextTo: isoDateOnly(85), notes: "", acts: [] },
    ],
    industrial: [
      { id: "is1", kind: "ОПО", title: "ОПО «Установка пиролиза»", number: "А56-00123", validUntil: isoDateOnly(800), status: "действует", owner: "Павлова И.Д.", file: "Св_рег_ОПО.pdf", notes: "I класс опасности" },
      { id: "is2", kind: "лицензия", title: "Лицензия на эксплуатацию ВПО", number: "ВХ-00-012345", validUntil: isoDateOnly(28), status: "истекает", owner: "Соколова Е.В.", file: "Лицензия.pdf", notes: "Продление в работе" },
      { id: "is3", kind: "экспертиза", title: "ЭПБ реактора Р-101", number: "ЭПБ-2025-77", validUntil: isoDateOnly(300), status: "действует", owner: "Павлова И.Д.", file: "ЭПБ_Р101.pdf", notes: "" },
      { id: "is4", kind: "ПЛАС", title: "ПЛАС площадки «Восточная»", number: "ПЛАС-В-2026", validUntil: isoDateOnly(200), status: "действует", owner: "Новиков А.П.", file: "ПЛАС_Восток.pdf", notes: "Учения — апрель" },
      { id: "is5", kind: "диагностика", title: "НК трубопровода топливного газа", number: "НК-2026-019", validUntil: isoDateOnly(-4), status: "просрочено", owner: "Кузнецов А.М.", file: "Заявка_НК.pdf", notes: "Перенос из-за ППР" },
      { id: "is6", kind: "наряд-допуск", title: "Наряд на ГОР № 48", number: "ГОР-48", validUntil: isoDateOnly(1), status: "действует", owner: "Новиков А.П.", file: "ГОР-48.pdf", notes: "Связан с подрядчиком Вершина" },
      { id: "is7", kind: "инцидент на оборудовании", title: "Отказ уплотнения Н-1204 (архив)", number: "ИО-2025-11", validUntil: isoDateOnly(-200), status: "архив", owner: "Иванова А.С.", file: "ИО-2025-11.pdf", notes: "Связан с LTI НХТК-2025-047" },
    ],
    inspections: [
      {
        id: "insp1",
        body: "Ростехнадзор",
        type: "плановая",
        period: "17–21 марта 2026",
        start: isoDateOnly(5),
        end: isoDateOnly(9),
        status: "назначена",
        fines: 0,
        attachments: ["уведомление.pdf"],
        prescriptions: [{ id: "pp1", text: "Подготовить журнал диагностик и ПЛАС", due: isoDateOnly(4), owner: "Павлова И.Д.", status: "открыто" }],
      },
      {
        id: "insp2",
        body: "ГИТ",
        type: "внеплановая",
        period: "февраль 2026",
        start: isoDateOnly(-28),
        end: isoDateOnly(-26),
        status: "предписание",
        fines: 0,
        attachments: ["предписание_ГИТ.pdf"],
        prescriptions: [
          { id: "pp2", text: "Актуализировать карты СОУТ слесаря РМЦ", due: isoDateOnly(-2), owner: "Иванова А.С.", status: "просрочено" },
          { id: "pp3", text: "Доукомплектовать аптечки смены Б", due: isoDateOnly(6), owner: "Козлов Д.П.", status: "открыто" },
        ],
      },
      {
        id: "insp3",
        body: "МЧС",
        type: "плановая",
        period: "декабрь 2025",
        start: isoDateOnly(-90),
        end: isoDateOnly(-88),
        status: "закрыта",
        fines: 0,
        attachments: ["акт_МЧС.pdf"],
        prescriptions: [{ id: "pp4", text: "Замена доводчика ПД-А-03", due: isoDateOnly(-40), owner: "Смирнова О.И.", status: "устранено" }],
      },
      {
        id: "insp4",
        body: "Росприроднадзор",
        type: "документарная",
        period: "январь 2026",
        start: isoDateOnly(-50),
        end: isoDateOnly(-40),
        status: "предписание",
        fines: 180000,
        attachments: ["акт_РПН.pdf"],
        prescriptions: [{ id: "pp5", text: "Скорректировать график вывода ила", due: isoDateOnly(12), owner: "Волкова М.А.", status: "открыто" }],
      },
    ],
    links: [
      { id: "l1", title: "FineBI НХТК", url: "#/finebi", description: "Корпоративная аналитика HSE", group: "системы", icon: "finebi", hidden: false },
      { id: "l2", title: "SharePoint ОТ", url: "https://sharepoint.nhtk.local/hse", description: "Файловое хранилище ЛНА", group: "системы", icon: "folder", hidden: false },
      { id: "l3", title: "ЭДО", url: "https://edo.nhtk.local", description: "Согласование приказов и актов", group: "системы", icon: "file", hidden: false },
      { id: "l4", title: "СДО обучение", url: "#/training", description: "Электронные курсы", group: "обучение", icon: "grad", hidden: false },
      { id: "l5", title: "КонсультантПлюс / НПА", url: "https://www.consultant.ru", description: "Внешние нормативные акты", group: "НПА", icon: "book", hidden: false },
      { id: "l6", title: "Пожарная охрана", url: "tel:101", description: "101 / внутренний 10-01", group: "экстренные", icon: "phone", hidden: false },
      { id: "l7", title: "Медпункт НХТК", url: "tel:+78555313000", description: "Круглосуточно, корпус А", group: "экстренные", icon: "phone", hidden: false },
      { id: "l8", title: "Газовая спасательная", url: "tel:104", description: "Внутренний 10-04", group: "экстренные", icon: "phone", hidden: false },
      { id: "l9", title: "Telegram HSE НХТК", url: "https://t.me/nhtk_hse", description: "Оперативные сообщения и контакты по безопасности", group: "системы", icon: "tg", hidden: false },
    ],
    forum: [
      {
        id: "fo1",
        title: "Антискользящие покрытия: чей опыт лучше?",
        body: "После LTI на Н-1204 ищем покрытие, которое держит масло. Кто уже применял на насосных?",
        authorId: "u9",
        date: isoDays(-12),
        tags: ["практика", "полимеры"],
        likes: ["u1", "u3", "u7"],
        hidden: false,
        pinned: true,
        attachments: [],
        comments: [
          { id: "fc1", authorId: "u1", date: isoDays(-11), text: "На складе ГСМ стоит «Полимер-Грит 2». Могу показать образец." },
          { id: "fc2", authorId: "u7", date: isoDays(-10), text: "На пиролизе не подошло — отслаивается от тепла. Смотрите термостойкое." },
        ],
      },
      {
        id: "fo2",
        title: "Подрядчики на высоте — напоминание",
        body: "Сегодня снова строп за трубу. Коллеги, останавливайте работы, это не «мелочь».",
        authorId: "u7",
        date: isoDays(-1),
        tags: ["подрядчики", "высота"],
        likes: ["u1", "u4", "u11", "u3"],
        hidden: false,
        pinned: false,
        attachments: ["фото"],
        comments: [{ id: "fc3", authorId: "u3", date: isoDays(-1, 16), text: "Вынес в чемпионат как кейс этапа." }],
      },
      {
        id: "fo3",
        title: "Черновик обсуждения (скрыто)",
        body: "Тестовое сообщение, скрыто модератором.",
        authorId: "u13",
        date: isoDays(-20),
        tags: [],
        likes: [],
        hidden: true,
        pinned: false,
        attachments: [],
        comments: [],
      },
    ],
    policyAck: [{ id: "pa1", docId: "policy", userId: "u2", date: isoDays(-15) }],
  };
}

export const SEED_VERSION = "nhtk-hse-v3";
